/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#e9b3ff",
        "outline-variant": "#45474b",
        "on-error": "#690005",
        "on-surface": "#dfe2eb",
        "tertiary-container": "#210032",
        "on-secondary-container": "#006c71",
        "primary-fixed-dim": "#bec2ff",
        "surface-container": "#1c2026",
        "on-primary-fixed": "#000569",
        "inverse-on-surface": "#2d3137",
        "primary-fixed": "#e0e0ff",
        "on-tertiary-container": "#b24de5",
        "on-primary": "#000ca5",
        "on-secondary": "#003739",
        "inverse-primary": "#3846ec",
        "secondary": "#e6feff",
        "surface-dim": "#10141a",
        "primary-container": "#00024a",
        "surface-variant": "#31353c",
        "tertiary-fixed": "#f6d9ff",
        "outline": "#8f9095",
        "surface-container-high": "#262a31",
        "tertiary-fixed-dim": "#e9b3ff",
        "primary": "#bec2ff",
        "secondary-fixed-dim": "#00dce5",
        "on-surface-variant": "#c6c6cb",
        "on-primary-fixed-variant": "#1523d6",
        "on-tertiary-fixed": "#310048",
        "secondary-fixed": "#63f7ff",
        "surface-container-highest": "#31353c",
        "secondary-container": "#00f4fe",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "background": "#10141a",
        "on-primary-container": "#5f6cff",
        "on-background": "#dfe2eb",
        "surface-container-low": "#181c22",
        "surface-container-lowest": "#0a0e14",
        "inverse-surface": "#dfe2eb",
        "on-tertiary-fixed-variant": "#7200a3",
        "on-secondary-fixed": "#002021",
        "surface-bright": "#353940",
        "on-tertiary": "#510074",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004f53",
        "surface-tint": "#bec2ff",
        "surface": "#10141a"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
